import numpy as np

twoDArray = np.array([[1,2], [3,4]])
print (twoDArray)
print ("")
print (twoDArray[0])
print ("")
print (twoDArray[0][1])
print ("")
threeDArray = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print (threeDArray)
print ("")
print(threeDArray[0])
print ("")
print (threeDArray[0][1][0])
print ("")
print (threeDArray[:,:, :1])
print ("")
print (threeDArray[:1])
print ("")
print (threeDArray[:, :1])
print ("")
print (threeDArray[:][:1])
print(" ")
print ("start")
print (threeDArray[:][:])
print (" ")
print ("end")
print (threeDArray[:][:][:1]) # How do these even work????